# See the details of 'training_args' and 'compression_args' from the websites: https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/training_args.py and https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/compression_args.py
data_args:
    train_path: ./data/modeling/text_classification/model_train/uie/train.txt
    dev_path: ./data/modeling/text_classification/model_train/uie/dev.txt
    max_seq_length: 512

model_args:
    model_name_or_path: uie-base

training_args:
    output_dir: ./models/text_classification/uie/checkpoints/model_best
    overwrite_output_dir: True
    do_train: True
    do_eval: True
    do_predict: True
    do_export: True
    do_compress: False
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    learning_rate: 1e-3
    weight_decay: 0.0
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_epsilon: 1e-8
    max_grad_norm: 1.0
    num_train_epochs: 0.2
    lr_scheduler_type: linear
    warmup_ratio: 0.0
    warmup_steps: 0
    logging_steps: 10
    save_strategy: steps
    save_steps: 200
    eval_steps: 200
    save_total_limit: null
    seed: 1000
    device: gpu # or cpu
    disable_tqdm: True
    label_names: ['start_positions', 'end_positions']
    load_best_model_at_end: True
    metric_for_best_model: eval_f1
    resume_from_checkpoint: null
