labelstudio_file: "./data/modeling/information_extraction/label_studio/input_example.json"
save_dir: "./data/modeling/information_extraction/model_train/"
seed: 1000
split_ratio: [0.8, 0.1, 0.1]
is_shuffle: True
is_regularize_data: False
