# See the details of 'training_args' and 'compression_args' from the websites: https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/training_args.py and https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/compression_args.py
data_args:
    # test_path: ./data/modeling/text_classification/model_train/utc/dataset/test.txt # or utc/uie_processed_dataset/test.txt
    test_path: ./data/modeling/text_classification/model_train/utc/uie_processed_dataset/test.txt
    threshold: 0.5

model_args:
    model_name_or_path: utc-base
    checkpoint_path: ./models/text_classification/utc/checkpoints/model_best

eval_args:
    output_dir: ./models/text_classification/utc/checkpoints/model_best/test_results
    max_seq_length: 768
    seed: 30678
    device: gpu # or cpu
    disable_tqdm: True
    metric_for_best_model: macro_f1
    freeze_dropout: True
    save_plm: True
    freeze_plm: True
