# See the details of 'training_args' and 'compression_args' from the websites: https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/training_args.py and https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/compression_args.py
data_args:
    # dataset_path: ./data/modeling/text_classification/model_train/utc/dataset # "./dataset/uie_processed_dataset"
    dataset_path: ./data/modeling/text_classification/model_train/utc/uie_processed_dataset
    train_file: train.txt
    dev_file: dev.txt

model_args:
    model_name_or_path: utc-base

training_args:
    output_dir: ./models/text_classification/utc/checkpoints/model_best
    max_seq_length: 768
    overwrite_output_dir: True
    do_train: True
    do_eval: True
    do_export: True
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 8
    learning_rate: 1e-4
    weight_decay: 0.0
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_epsilon: 1e-8
    max_grad_norm: 1.0
    num_train_epochs: 0.1
    lr_scheduler_type: linear
    warmup_ratio: 0.0
    warmup_steps: 0
    logging_steps: 5
    save_strategy: steps
    save_steps: 200
    eval_steps: 200
    save_total_limit: 1
    seed: 30678
    device: gpu # or "cpu"
    disable_tqdm: True
    load_best_model_at_end: True
    metric_for_best_model: macro_f1
    resume_from_checkpoint: null
    save_plm: True
